package nz.ac.aut.ense701.gui;

import nz.ac.aut.ense701.gameModel.Game;
import nz.ac.aut.ense701.gameModel.Terrain;

import javax.swing.*;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import java.awt.*;

/*
 * Panel for representing a single GridSquare of the island on the GUI.
 * 
 * @author AS
 * 
 * @version 1.0 - created
 */

public class GridSquarePanel extends JPanel
{
	private static final Border normalBorder = new LineBorder(Color.BLACK, 1);
	private static final Border activeBorder = new LineBorder(Color.RED, 3);
	private JLabel lblText;
	private Game               game;
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private int                row, column;
	// End of variables declaration//GEN-END:variables

	/**
	 * Creates new GridSquarePanel.
	 *
	 * @param game   the game to represent
	 * @param row    the row to represent
	 * @param column the column to represent
	 */
	public GridSquarePanel(Game game, int row, int column)
	{
		this.game = game;
		this.row = row;
		this.column = column;
		initComponents();
	}

	/**
	 * Updates the representation of the grid square panel.
	 */
	public void update()
	{
		// get the GridSquare object from the world
		Terrain terrain = game.getTerrain(row, column);
		boolean squareVisible = game.isVisible(row, column);
		boolean squareExplored = game.isExplored(row, column);
		ImageIcon icon;
		Color color;

		switch (terrain)
		{
			case SAND:
				icon = new ImageIcon("resources/Sand_Tile.jpg");
				break;
			case FOREST:
				icon = new ImageIcon("resources/Forest_Tile.jpg");
				break;
			case WETLAND:
				icon = new ImageIcon("resources/Wetland_Tile.jpg");
				break;
			case SCRUB:
				icon = new ImageIcon("resources/Scrub_Tile.jpg");
				break;
			case WATER:
				icon = new ImageIcon("resources/Water_Tile.jpg");
				break;
			default:
				icon = new ImageIcon("resources/Unexplored_Tile.jpg");
				break;
		}

		if (squareExplored || squareVisible)
		{
			// Set the colour.
			/*if (squareVisible && !squareExplored)
			{
				// When explored the colour is brighter
				color = new Color(Math.min(255, color.getRed() + 128), Math.min(255, color.getGreen() + 128),
						Math.min(255, color.getBlue() + 128));
			}*/
			lblText.setIcon(icon);
			// Set the text of the JLabel according to the occupant
			lblText.setText(game.getOccupantStringRepresentation(row, column));
			// set border colour according to
			// whether the player is in the grid square or not
			setBorder(game.hasPlayer(row, column) ? activeBorder : normalBorder);
		}
		else
		{
			lblText.setText("");
			icon = new ImageIcon("resources/Unexplored_Tile.jpg");
			lblText.setIcon(icon);
			setBorder(normalBorder);
		}
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")


	private void initComponents()
	{
		lblText = new JLabel();

		setBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		setLayout(new BorderLayout());

		lblText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		lblText.setHorizontalAlignment(SwingConstants.CENTER);
		lblText.setText("content");
		lblText.setOpaque(true);
		add(lblText, BorderLayout.CENTER);
	}
}
